sources:
- function: scrape_homepage
  id: news_vnexpress
  language: vietnamese
  module: scraper.vnexpress_scraper
  name: VnExpress News
  status: standby
  type: news
- function: scrape_homepage
  id: news_tinhte
  language: vietnamese
  module: scraper.tinhte_scraper
  name: Tinhte News
  status: standby
  type: news
- function: scrape_homepage
  id: news_cnn
  language: english
  module: scraper.cnn_scraper
  name: CNN News
  status: active
  type: news
