import sys
from pathlib import Path
from cryptography.fernet import Fernet
from dotenv import load_dotenv
from pydantic_settings import BaseSettings, SettingsConfigDict


CONSOLE_ROOT = Path(__file__).parent.parent
PROJECT_ROOT = CONSOLE_ROOT.parent

# Make pipeline credentials and runtime config available to console-invoked core modules.
load_dotenv(PROJECT_ROOT / "pipeline.env", override=False)
load_dotenv(CONSOLE_ROOT / ".env", override=True)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=CONSOLE_ROOT / ".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Database
    DATABASE_URL: str = "postgresql://postgres:password@localhost:5432/ai_media"

    # Redis
    REDIS_URL: str = "redis://localhost:6379/0"

    # JWT
    JWT_SECRET: str = "change-me"
    JWT_ALGORITHM: str = "HS256"
    JWT_EXPIRE_MINUTES: int = 1440

    # Fernet encryption key for OAuth secrets
    FERNET_KEY: str = ""

    # Path to root project (so we can import core pipeline modules)
    CORE_PIPELINE_PATH: str = ".."

    # Server
    CONSOLE_PORT: int = 8080
    FRONTEND_ORIGIN: str = "http://localhost:5173"

    # Environment
    ENV: str = "development"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Add the core pipeline root to sys.path so we can do:
        #   from rag.script_writer import generate_script
        configured_path = Path(self.CORE_PIPELINE_PATH)
        if configured_path.is_absolute():
            core_path = configured_path.resolve()
        else:
            core_path = (CONSOLE_ROOT / configured_path).resolve()
        if core_path not in sys.path:
            sys.path.insert(0, str(core_path))

    def validate_fernet_key(self) -> None:
        key = self.FERNET_KEY.strip()
        if not key:
            raise ValueError(
                "FERNET_KEY is not set. Generate one with: "
                "python3 -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
            )
        try:
            Fernet(key.encode())
        except Exception as exc:
            raise ValueError(
                "FERNET_KEY is invalid. It must be a 32-byte url-safe base64 string generated by Fernet.generate_key()."
            ) from exc


settings = Settings()
